printWidth: 80
useTabs: false
tabWidth: 4
semi: true
singleQuote: true
trailingComma: es5
bracketSpacing: true
jsxBracketSameLine: false
arrowParens: always
overrides:
  - files:
      - 'package.json'
      - '*.yml'
      - '*.yaml'
      - '*.md'
      - '.*'
    options:
      tabWidth: 2
  - files:
      - '*.libraries.yml'
    options:
      printWidth: 200
  - files:
      - '*.module'
    options:
      parser: 'php'
